from datetime import datetime
from typing import Any

from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class EngineeringDoc(Base):
    """One CAD drawing — either analyzed from an upload (.dxf, or .dwg
    converted via ODA File Converter) or generated by Loki from a text
    request. extracted_data holds whatever cad_parser.parse_drawing()
    could pull out (entity counts, text annotations, dimension values);
    null for generated drawings that were never re-analyzed.

    project_id (nullable) optionally attaches this drawing to a Project as
    a reference file — it is NOT the source of that project's BOM (the BOM
    is computed by led_bom.calculate_bom() from declared dimensions/pitch/
    screen type, per the plan's decision that parsing a real BOM out of
    arbitrary CAD annotation text is infeasible)."""

    __tablename__ = "engineering_docs"

    id: Mapped[int] = mapped_column(primary_key=True)
    project_name: Mapped[str] = mapped_column(String(255))
    file_path: Mapped[str] = mapped_column(String(1024))
    doc_type: Mapped[str] = mapped_column(String(10))  # 'dxf' | 'dwg' | 'cdr'
    extracted_data: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    is_generated: Mapped[bool] = mapped_column(Boolean, default=False)
    project_id: Mapped[int | None] = mapped_column(ForeignKey("projects.id"), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
