"""add telegram_message_id to messages

Revision ID: 432b5f5fb157
Revises: 509f5f38851d
Create Date: 2026-08-09 18:33:38.242655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432b5f5fb157'
down_revision: Union[str, None] = '509f5f38851d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('telegram_message_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_messages_telegram_message_id'), 'messages', ['telegram_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_telegram_message_id'), table_name='messages')
    op.drop_column('messages', 'telegram_message_id')
    # ### end Alembic commands ###
