"""add reminders table

Revision ID: 5f0e4c22c638
Revises: 432b5f5fb157
Create Date: 2026-08-09 18:39:58.457419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0e4c22c638'
down_revision: Union[str, None] = '432b5f5fb157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('target_username', sa.String(length=255), nullable=True),
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('notify_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cron_rule', sa.String(length=100), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_chat_id'), 'reminders', ['chat_id'], unique=False)
    op.create_index(op.f('ix_reminders_notify_at'), 'reminders', ['notify_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_notify_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_chat_id'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
